# 7. 오류처리
깨끗한 코드와 오류처리는 확실히 연관성이 있다. 상당수 코드 기반은 전적으로 오류 처리 코드에 좌우된다.  
여기서 좌우된다는 표현은 코드 기반이 오류만 처리한다는 의미가 아니다. 여기저기 흩어진 오류 처리 코드 때문에 실제 코드가 하는 일을 파악하기가 거의 불가능하다는 의미다.  
오류 처리는 중요하지만 오류 처리 코드로 인해 프로그램 논리를 이해하기 어려워진다면 깨끗한 코드라 부르기 어렵다.  
이 장에서는 꺠긋하게 오류를 처리하는 기법과 고려 사항 몇 가지를 소개한다.  

## 오류 코드보다 예외를 사용하라!
~~~java
// Bad : 오류 코드 사용 
public class DeviceController {
  ...
  public void sendShutDown() {
    DeviceHandle handle = getHandle(DEV1);
    // 디바이스 상태를 점검한다.
    if (handle != DeviceHandle.INVALID) {
      // 레코드 필드에 디바이스 상태를 저장한다.
      retrieveDeviceRecord(handle);
      // 디바이스가 일시정지 상태가 아니라면 죵료한다.
      if (record.getStatus() != DEVICE_SUSPENDED) {
        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
      } else {
        logger.log("Device suspended. Unable to shut down");
      }
    } else {
      logger.log("Invalid handle for: " + DEV1.toString());
    }
  }
  ...
}
~~~
+ 호출자 코드가 복잡해진다.(함수를 호출한 즉시 오류를 확인해야 하기 때문)
+ 오류가 발생하면 예외를 던지는 편이 낫다.(논리가 오류 처리 코드와 뒤섞이지 않으니 깔끔해진다.)
~~~java
// Good : 오류를 발견하면 예외를 던지는 코드
public class DeviceController {
  ...
  public void sendShutDown() {
    try {
      tryToShutDown();
    } catch (DeviceShutDownError e) {
      logger.log(e);
    }
  }
    
  private void tryToShutDown() throws DeviceShutDownError {
    DeviceHandle handle = getHandle(DEV1);
    DeviceRecord record = retrieveDeviceRecord(handle);
    pauseDevice(handle); 
    clearDeviceWorkQueue(handle); 
    closeDevice(handle);
  }
  
  private DeviceHandle getHandle(DeviceID id) {
    ...
    throw new DeviceShutDownError("Invalid handle for: " + id.toString());
    ...
  }
  ...
}
~~~
+ 가독성은 물론, **논리 로직**과 **오류처리 로직**을 분리했기 때문에 각 개념을 독립적으로 살펴보고 이해할 수 있다.  

## Try-Catch-Finally 문부터 작성하라!
어떤 면에서 try 블록은 트랜잭션과 비슷하다. try 블록에서 무슨 일이 생기든지 catch 블록은 프로그램 상태를 일관성 있게 유지해야 한다.  
그러므로 예외가 발생할 코드를 짤 때는 try-catch-finally 문으로 시작하는 편이 낫다.  
(그러면 try 블록에서 무슨 일이 생기든지 호출자가 기대하는 상태를 정의하기 쉬워진다.)  

예제: 파일을 열어 직렬화된 객체 몇개를 읽어 들이는 코드
~~~java
// 파일이 없으면 예외를 던지는지 알아보는 단위 테스트
// 예외를 던지지 않으므로 단위 테스트는 실
@Test(expected = StorageException.class)
public void retrieveSectionShoudThrowOnInvalidFileName() {
   sectionStore.retrieveSection("invalid - file");
}
  
public List<RecordedGrip> retrieveSection(String sectionName) {
	// 실제로 구현할 때까지 비어있는 더미를 반환한다.
	return new ArrayList<RecordedGrip>();
}
~~~
~~~java
// 예외를 던지므로 테스트를 통과한다.
public List<RecordedGrip> retrieveSection(String sectionName) {
	try {
      FileInputStream stream = new FileInputStream(sectionName)
    } catch (Exception e) {
      throw new StorageException("retrieval error", e);
    }
	return new ArrayList<RecordedGrip>();
}
~~~
~~~java
// 리팩터링
// catch 블록에서 예외 유형을 좁혀, 실제로 FileInputStream 생성자가 던지는 FileNotFoundException을 잡아낸다.
public List<RecordedGrip> retrieveSection(String sectionName) {
	try {
	  FileInputStream stream = new FileInputStream(sectionName);
	  stream.close();
	} catch (FileNotFoundException e) {
	  throw new StorageException("retrieval error", e);
	}
	return new ArrayList<RecordedGrip>();
}
 ~~~